name: Release superfile

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]

jobs:
  superfile:
    runs-on: ubuntu-24.04
    steps:
    - id: changelog
      uses: zhaojh329/auto-changelog@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - id: checkout
      uses: actions/checkout@v4
    - name: Download lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.3.5"
    - id: superfile
      run: |
        cd luapack
        lua main.lua ../addons/igs-core/lua superfile.json
    - id: igsmod
      run: |
        cd addons
        zip -x "*.DS_Store" -r igs-mod.zip igs-modification/
    - id: release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{steps.changelog.outputs.changelog}}
        # tag_name: asdasd
        #draft: true
        prerelease: false
        files: |
          luapack/superfile.json
          addons/igs-mod.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
